# 기존 거래내역 데이터에 동데이터 전처리 후 변수 추가

In [7]:

import pandas as pd
import numpy as np
import glob
prop = pd.read_csv("prop_concat2015~2020.csv", encoding='utf-8', index_col = 0)
prop.head()

,전용면적(㎡),계약일,거래금액(만원),층,연도,월,연수,시,구,동,주소
0,2.0,11,60000,4.0,2015,1.0,7.0,서울특별시,강남구,개포동,서울특별시 강남구 언주로 103
1,2.0,3,65000,4.0,2015,2.0,7.0,서울특별시,강남구,개포동,서울특별시 강남구 언주로 103
2,2.0,7,62500,3.0,2015,2.0,7.0,서울특별시,강남구,개포동,서울특별시 강남구 언주로 103
3,2.0,16,68000,4.0,2015,3.0,7.0,서울특별시,강남구,개포동,서울특별시 강남구 언주로 103
4,2.0,29,73000,4.0,2015,1.0,7.0,서울특별시,강남구,개포동,서울특별시 강남구 언주로 3

In [8]:
#서울시 주민등록인구 (동별) 통계
#https://data.seoul.go.kr/dataList/10043/S/2/datasetView.do

df1 = pd.read_csv('seoul_data/seoul_dt1.txt',delimiter = '\t', skipinitialspace=True, usecols = 
                  ['기간','자치구','행정동','인구.3','인구.6','세대당인구'])
df1.rename(columns={'행정동':'동', '인구.3' : '내국인 인구', '인구.6': '외국인 인구'}, inplace = True)

df1

       기간  자치구     동     내국인 인구   외국인 인구  세대당인구
0      기간  자치구   행정동        한국인      외국인  세대당인구
1      기간  자치구   행정동          계        계  세대당인구
2    2019   합계    합계  9,729,107  281,876   2.25
3    2019  종로구    소계    151,290   10,579   2.05
4    2019  종로구   사직동      9,535      280   2.06
..    ...  ...   ...        ...      ...    ...
447  2019  강동구  둔촌1동        268       15   1.63
448  2019  강동구  둔촌2동     27,624      128   2.46
449  2019  강동구  암사1동     36,368      325   2.25
450  2019  강동구  천호2동     35,101      803   1.99
451  2019  강동구    길동     46,050      317   2.24

[452 rows x 6 columns]

In [9]:
#서울시 고령자현황 (동별) 통계
#https://data.seoul.go.kr/dataList/10020/S/2/datasetView.do


df2 = pd.read_csv('seoul_data/seoul_dt2.txt',delimiter = '\t', skipinitialspace=True, usecols = ['기간','자치구','동','65세이상 인구','65세이상 인구.6'])
df2.rename(columns={'65세이상 인구':'65세이상 내국인 인구', '65세이상 인구.6' : '65세이상 외국인 인구'}, inplace = True)
df2

       기간  자치구     동 65세이상 내국인 인구 65세이상 외국인 인구
0      기간  자치구     동           합계          외국인
1      기간  자치구     동            계            계
2    2019   합계    합계    1,485,272        6,608
3    2019  종로구    소계       27,519          201
4    2019  종로구   사직동        1,778           11
..    ...  ...   ...          ...          ...
447  2019  강동구  둔촌1동           94            1
448  2019  강동구  둔촌2동        4,010            1
449  2019  강동구  암사1동        5,623           14
450  2019  강동구  천호2동        5,692           20
451  2019  강동구    길동        7,125            5

[452 rows x 5 columns]

In [10]:
#서울시 국민기초생활보장 수급자 (동별) 통계
#https://data.seoul.go.kr/dataList/10113/S/2/datasetView.do


df4 = pd.read_csv('seoul_data/seoul_dt4.txt',delimiter = '\t', skipinitialspace=True, 
                  usecols = ['기간','자치구','동','총 수급자'])
df4

       기간  자치구     동    총 수급자
0      기간  자치구     동       가구
1    2019   합계    합계  221,695
2    2019   본청    본청        -
3    2019  종로구    소계    3,413
4    2019  종로구   사직동      101
..    ...  ...   ...      ...
472  2019  강동구  둔촌2동      347
473  2019  강동구  암사1동    1,034
474  2019  강동구  천호2동    1,207
475  2019  강동구    길동      872
476  2019  강동구    기타        5

[477 rows x 4 columns]

In [11]:
#서울시 인구밀도 (동별) 통계
#https://data.seoul.go.kr/dataList/10584/S/2/datasetView.do


df5 = pd.read_csv('seoul_data/seoul_dt5.txt',delimiter = '\t', skipinitialspace=True, 
                  usecols = ['기간','자치구','동','면적','인구밀도'])
df5['기간'] = df5.copy()['기간'].astype(str)
df5

       기간  자치구     동      면적    인구밀도
0    2019   합계    합계  605.24  16,541
1    2019  종로구    소계   23.91   6,769
2    2019  종로구   사직동    1.23   7,980
3    2019  종로구   삼청동    1.49   2,011
4    2019  종로구   부암동    2.27   4,648
..    ...  ...   ...     ...     ...
445  2019  강동구  둔촌1동    0.92     308
446  2019  강동구  둔촌2동    0.98  28,318
447  2019  강동구  암사1동    1.02  35,974
448  2019  강동구  천호2동    1.57  22,869
449  2019  강동구    길동    2.17  21,367

[450 rows x 5 columns]

In [12]:
#서울시 독거노인 현황 (성별/동별) 통계
#https://data.seoul.go.kr/dataList/10178/S/2/datasetView.do


df6 = pd.read_csv('seoul_data/seoul_dt6.txt',delimiter = '\t', skipinitialspace=True, usecols = 
                  ['기간','자치구','동','합계'])
df6.rename(columns={'합계' : '독거노인 합계'}, inplace = True)
df6

       기간  자치구     동  독거노인 합계
0      기간  자치구     동        계
1    2019   합계    합계  343,567
2    2019  종로구    소계    9,149
3    2019  종로구   사직동      439
4    2019  종로구   삼청동      167
..    ...  ...   ...      ...
446  2019  강동구  둔촌1동        3
447  2019  강동구  둔촌2동      775
448  2019  강동구  암사1동    1,304
449  2019  강동구  천호2동    1,538
450  2019  강동구    길동    1,455

[451 rows x 4 columns]

In [13]:
#서울시 출생사망(동별) 통계
#https://data.seoul.go.kr/dataList/425/S/2/datasetView.do


df7 = pd.read_csv('seoul_data/seoul_dt7.txt',delimiter = '\t', skipinitialspace=True, usecols = 
                  ['기간','자치구','행정동','출생','사망'])
df7.rename(columns={'행정동':'동'}, inplace = True)
df7

       기간  자치구     동      출생      사망
0      기간  자치구   행정동       계       계
1    2019   합계    합계  53,673  43,829
2    2019  종로구    소계     673     854
3    2019  종로구   사직동      41      59
4    2019  종로구   삼청동      10      15
..    ...  ...   ...     ...     ...
446  2019  강동구  둔촌1동       2       1
447  2019  강동구  둔촌2동     141     128
448  2019  강동구  암사1동     216     174
449  2019  강동구  천호2동     232     170
450  2019  강동구    길동     228     205

[451 rows x 5 columns]

In [14]:
#서울시 의료기관 (동별) 통계
#https://data.seoul.go.kr/dataList/10123/S/2/datasetView.do


df8 = pd.read_csv('seoul_data/seoul_dt8.txt',delimiter = '\t', skipinitialspace=True, usecols = 
                  ['기간','자치구','동','합계'])
df8.rename(columns={'합계':'의료기관 합계'}, inplace = True)
df8['기간'] = df8.copy()['기간'].astype(str)

df8

       기간  자치구     동 의료기관 합계
0    2019   합계    합계   5,698
1    2019  종로구    소계      77
2    2019  종로구   사직동      10
3    2019  종로구   삼청동       2
4    2019  종로구   부암동       3
..    ...  ...   ...     ...
442  2019  강동구  성내3동      12
443  2019  강동구  둔촌2동      18
444  2019  강동구  암사1동      20
445  2019  강동구  천호2동      10
446  2019  강동구    길동      22

[447 rows x 4 columns]

In [15]:
#서울시 동 공무원 (정원/동별) 통계
#https://data.seoul.go.kr/dataList/10159/S/2/datasetView.do


df10 = pd.read_csv('seoul_data/seoul_dt10.txt',delimiter = '\t')
df10.rename(columns={'계':'동 공무원 합계'}, inplace = True)
df10['기간'] = df10.copy()['기간'].astype(str)
df10.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 450 entries, 0 to 449
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   기간        450 non-null    object
 1   자치구       450 non-null    object
 2   동         450 non-null    object
 3   동 공무원 합계  450 non-null    object
 4   5급        450 non-null    object
 5   6급        450 non-null    object
 6   7급        450 non-null    object
 7   8급        450 non-null    object
 8   9급        450 non-null    object
dtypes: object(9)
memory usage: 31.8+ KB

In [16]:
#전처리한 dfs를 merge하고 다시 전처리

dfs = df1.merge(df2,on=('기간','동','자치구'),how='left').merge(df4,on=('기간','동','자치구'),how='left').fillna('void').merge(df5,on=('기간','동','자치구'),how='left').merge(df6,on=('기간','동','자치구'),how='left').merge(df7,on=('기간','동','자치구'),how='left')
dfs

,기간,자치구,동,내국인 인구,외국인 인구,세대당인구,65세이상 내국인 인구,65세이상 외국인 인구,총 수급자,면적,인구밀도,독거노인 합계,출생,사망
0,기간,자치구,행정동,한국인,외국인,세대당인구,void,void,void,NaN,NaN,NaN,계,계
1,기간,자치구,행정동,계,계,세대당인구,void,void,void,NaN,NaN,NaN,계,계
2,2019,합계,합계,"9,729,107","281,876",2.25,"1,485,272","6,608","221,695",605.24,"16,541","343,567","53,673","43,829"
3,2019,종로구,소계,"151,290","10,579",2.05,"27,519",201,"3,413",23.91,"6,769","9,149",673,854
4,2019,종로구,사직동,"9,535",280,2.06,"1,778",11,101,1.23,"7,980",439,41,59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
447,2019,강동구,둔촌1동,268,15,1.63,94,1,1,0.92,308,3,2,1
448,2019,강동구,둔촌2동,"27,624",128,2.46,"4,010",1,347,0.98,"28,318",775,141,128
449,2019,강동구,암사1동,"36,368",325,2.25,"5,623",14,"1,034",1.02,"35,974","1,304",216,174
450,2019,강동구,천호2동,"35,101",803,1.99,"5,692",20,"1,207",1.57,"22,869","1,538",232,170
451,2019,강동구,길동,"46,050",317,2.24,"7,125",5,872,2.17,"21,367","1,455",228,205

In [17]:
#dfs null value check

dfs.isnull().sum()

기간              0
자치구             0
동               0
내국인 인구          0
외국인 인구          0
세대당인구           0
65세이상 내국인 인구    0
65세이상 외국인 인구    0
총 수급자           0
면적              2
인구밀도            2
독거노인 합계         2
출생              0
사망              0
dtype: int64

In [18]:
#null값 drop

dfs['면적'].dropna(axis=0)
dfs['인구밀도'].dropna(axis=0)
dfs['독거노인 합계'].dropna(axis=0)

2      343,567
3        9,149
4          439
5          167
6          346
        ...
447          3
448        775
449      1,304
450      1,538
451      1,455
Name: 독거노인 합계, Length: 450, dtype: object

In [19]:
#마포2동 마포3동을 숫자를 제거한뒤 마포동으로 변환을 함. 
#기존의 부동산 거래 데이터에는 마포2동 마포3동 모두 마포동으로 되어있기 때문
#동 column에 존재하는 불필요한 row 삭제

dfs['동'] = dfs.copy()['동'].str.replace('\d+', '')
dfs = dfs[((dfs['자치구']!='합계')&(dfs['동']!='소계')&(dfs['동']!='합계')&(dfs['기간']!='기간'))]
dfs

<ipython-input-19-7ee4b0dd4c81>:5: FutureWarning: The default value of regex will change from True to False in a future version.
  dfs['동'] = dfs.copy()['동'].str.replace('\d+', '')

,기간,자치구,동,내국인 인구,외국인 인구,세대당인구,65세이상 내국인 인구,65세이상 외국인 인구,총 수급자,면적,인구밀도,독거노인 합계,출생,사망
4,2019,종로구,사직동,"9,535",280,2.06,"1,778",11,101,1.23,"7,980",439,41,59
5,2019,종로구,삼청동,"2,758",239,1.98,664,21,30,1.49,"2,011",167,10,15
6,2019,종로구,부암동,"10,100",451,2.35,"1,762",6,103,2.27,"4,648",346,48,62
7,2019,종로구,평창동,"18,659",157,2.48,"3,263",13,106,8.87,"2,121",640,80,102
8,2019,종로구,무악동,"8,695",45,2.73,"1,413",-,110,0.36,"24,278",265,44,33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
447,2019,강동구,둔촌동,268,15,1.63,94,1,1,0.92,308,3,2,1
448,2019,강동구,둔촌동,"27,624",128,2.46,"4,010",1,347,0.98,"28,318",775,141,128
449,2019,강동구,암사동,"36,368",325,2.25,"5,623",14,"1,034",1.02,"35,974","1,304",216,174
450,2019,강동구,천호동,"35,101",803,1.99,"5,692",20,"1,207",1.57,"22,869","1,538",232,170
451,2019,강동구,길동,"46,050",317,2.24,"7,125",5,872,2.17,"21,367","1,455",228,205

In [20]:
#데이터를 열어보니 '-' 값이 있어 string으로 인식이 되어 dropna가 되지 않아 '-' value를 int 0으로 변환

dfs = dfs.replace(to_replace={"-":0})

In [21]:
dfs['기간'].unique()

array(['2019'], dtype=object)

In [22]:
#null value check
dfs.isnull().sum()

기간              0
자치구             0
동               0
내국인 인구          0
외국인 인구          0
세대당인구           0
65세이상 내국인 인구    0
65세이상 외국인 인구    0
총 수급자           0
면적              0
인구밀도            0
독거노인 합계         0
출생              0
사망              0
dtype: int64

In [23]:
dfs.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 424 entries, 4 to 451
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   기간            424 non-null    object
 1   자치구           424 non-null    object
 2   동             424 non-null    object
 3   내국인 인구        424 non-null    object
 4   외국인 인구        424 non-null    object
 5   세대당인구         424 non-null    object
 6   65세이상 내국인 인구  424 non-null    object
 7   65세이상 외국인 인구  424 non-null    object
 8   총 수급자         424 non-null    object
 9   면적            424 non-null    float64
 10  인구밀도          424 non-null    object
 11  독거노인 합계       424 non-null    object
 12  출생            424 non-null    object
 13  사망            424 non-null    object
dtypes: float64(1), object(13)
memory usage: 49.7+ KB

In [24]:
#datatype 변환 및 int로 변환하기 위해 value에 포함된 ',' 제거 후 int로 변환

dfs['내국인 인구'] = dfs.copy()['내국인 인구'].str.replace(pat=r'[^\w]', repl=r'', regex=True)
dfs['내국인 인구'] = dfs.copy()['내국인 인구'].astype(float)
dfs['외국인 인구'] = dfs.copy()['외국인 인구'].str.replace(pat=r'[^\w]', repl=r'', regex=True)
dfs['외국인 인구'] = dfs.copy()['외국인 인구'].astype(float)
dfs['세대당인구'] = dfs.copy()['세대당인구'].str.replace(pat=r'[^\w]', repl=r'', regex=True)
dfs['세대당인구'] = dfs.copy()['세대당인구'].astype(float)
dfs['65세이상 내국인 인구'] = dfs.copy()['65세이상 내국인 인구'].str.replace(pat=r'[^\w]', repl=r'', regex=True)
dfs['65세이상 내국인 인구'] = dfs.copy()['65세이상 내국인 인구'].astype(float)
dfs['65세이상 외국인 인구'] = dfs.copy()['65세이상 외국인 인구'].str.replace(pat=r'[^\w]', repl=r'', regex=True)
dfs['65세이상 외국인 인구'] = dfs.copy()['65세이상 외국인 인구'].str.replace(pat=r'[^\w]', repl=r'', regex=True)
dfs['65세이상 외국인 인구'] = dfs.copy()['65세이상 외국인 인구'].astype(float)
dfs['총 수급자'] = dfs.copy()['총 수급자'].str.replace(pat=r'[^\w]', repl=r'', regex=True)
dfs['총 수급자'] = dfs.copy()['총 수급자'].astype(float)
dfs['인구밀도'] = dfs.copy()['인구밀도'].str.replace(pat=r'[^\w]', repl=r'', regex=True)
dfs['인구밀도'] = dfs.copy()['인구밀도'].astype(float)
dfs['독거노인 합계'] = dfs.copy()['독거노인 합계'].str.replace(pat=r'[^\w]', repl=r'', regex=True)
dfs['독거노인 합계'] = dfs.copy()['독거노인 합계'].astype(float)
dfs['출생'] = dfs.copy()['출생'].str.replace(pat=r'[^\w]', repl=r'', regex=True)
dfs['출생'] = dfs.copy()['출생'].astype(float)
dfs['사망'] = dfs.copy()['사망'].str.replace(pat=r'[^\w]', repl=r'', regex=True)
dfs['사망'] = dfs.copy()['사망'].astype(float)

In [25]:
dfs

,기간,자치구,동,내국인 인구,외국인 인구,세대당인구,65세이상 내국인 인구,65세이상 외국인 인구,총 수급자,면적,인구밀도,독거노인 합계,출생,사망
4,2019,종로구,사직동,9535.0,280.0,206.0,1778.0,11.0,101.0,1.23,7980.0,439.0,41.0,59.0
5,2019,종로구,삼청동,2758.0,239.0,198.0,664.0,21.0,30.0,1.49,2011.0,167.0,10.0,15.0
6,2019,종로구,부암동,10100.0,451.0,235.0,1762.0,6.0,103.0,2.27,4648.0,346.0,48.0,62.0
7,2019,종로구,평창동,18659.0,157.0,248.0,3263.0,13.0,106.0,8.87,2121.0,640.0,80.0,102.0
8,2019,종로구,무악동,8695.0,45.0,273.0,1413.0,NaN,110.0,0.36,24278.0,265.0,44.0,33.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
447,2019,강동구,둔촌동,268.0,15.0,163.0,94.0,1.0,1.0,0.92,308.0,3.0,2.0,1.0
448,2019,강동구,둔촌동,27624.0,128.0,246.0,4010.0,1.0,347.0,0.98,28318.0,775.0,141.0,128.0
449,2019,강동구,암사동,36368.0,325.0,225.0,5623.0,14.0,1034.0,1.02,35974.0,1304.0,216.0,174.0
450,2019,강동구,천호동,35101.0,803.0,199.0,5692.0,20.0,1207.0,1.57,22869.0,1538.0,232.0,170.0
451,2019,강동구,길동,46050.0,317.0,224.0,7125.0,5.0,872.0,2.17,21367.0,1455.0,228.0,205.0

In [26]:
dfs['자치구'].unique()

array(['종로구', '중구', '용산구', '성동구', '광진구', '동대문구', '중랑구', '성북구', '강북구',
       '도봉구', '노원구', '은평구', '서대문구', '마포구', '양천구', '강서구', '구로구', '금천구',
       '영등포구', '동작구', '관악구', '서초구', '강남구', '송파구', '강동구'], dtype=object)

In [31]:
#dfsg DF를 group by를 통해 기간-자치구-동이 중복될시 mean값으로 변환
dfsg =dfs.groupby(['기간','자치구','동'], as_index=False).mean()

In [32]:
dfsg

,기간,자치구,동,내국인 인구,외국인 인구,세대당인구,65세이상 내국인 인구,65세이상 외국인 인구,총 수급자,면적,인구밀도,독거노인 합계,출생,사망
0,2019,강남구,개포동,15710.666667,80.666667,254.666667,2188.666667,3.666667,194.666667,1.756667,8861.666667,374.333333,70.333333,44.333333
1,2019,강남구,논현동,22373.000000,475.000000,90.500000,2920.500000,6.500000,321.500000,1.360000,16967.500000,520.500000,106.500000,85.000000
2,2019,강남구,대치동,28092.000000,165.000000,280.333333,2830.000000,5.000000,129.000000,1.173333,26625.000000,330.333333,70.000000,64.000000
3,2019,강남구,도곡동,28395.500000,136.000000,277.000000,3598.500000,9.500000,65.000000,1.020000,27972.000000,474.500000,151.000000,81.000000
4,2019,강남구,삼성동,22549.500000,247.500000,236.000000,2679.500000,7.000000,177.000000,1.590000,16214.000000,400.000000,138.000000,61.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
244,2019,중랑구,면목본동,35341.000000,854.000000,2.000000,5729.000000,5.000000,1332.000000,1.010000,35837.000000,1245.000000,201.000000,191.000000
245,2019,중랑구,묵동,27750.000000,208.500000,230.000000,4329.500000,8.000000,567.500000,0.950000,29221.500000,765.000000,172.000000,126.500000
246,2019,중랑구,상봉동,22422.500000,249.000000,211.500000,3125.000000,6.000000,754.500000,0.765000,29590.500000,1274.000000,147.500000,100.000000
247,2019,중랑구,신내동,31266.500000,113.000000,257.500000,4959.000000,3.000000,860.000000,1.760000,19137.000000,1310.000000,173.500000,176.500000
248,2019,중랑구,중화동,23723.000000,372.000000,21.000000,4023.500000,11.000000,988.000000,0.830000,29295.000000,938.500000,139.500000,126.500000

In [33]:
#동에서 숫자가 제대로 제거되었는지 확인
dfsg['동'].unique()

array(['개포동', '논현동', '대치동', '도곡동', '삼성동', '세곡동', '수서동', '신사동', '압구정동',
       '역삼동', '일원동', '일원본동', '청담동', '강일동', '고덕동', '길동', '둔촌동', '명일동',
       '상일동', '성내동', '암사동', '천호동', '미아동', '번동', '삼각산동', '삼양동', '송중동',
       '송천동', '수유동', '우이동', '인수동', '가양동', '공항동', '등촌동', '발산동', '방화동',
       '염창동', '우장산동', '화곡동', '화곡본동', '낙성대동', '난곡동', '난향동', '남현동', '대학동',
       '미성동', '보라매동', '서림동', '서원동', '성현동', '신림동', '신원동', '은천동', '인헌동',
       '조원동', '중앙동', '청룡동', '청림동', '행운동', '광장동', '구의동', '군자동', '능동',
       '자양동', '중곡동', '화양동', '가리봉동', '개봉동', '고척동', '구로동', '수궁동', '신도림동',
       '오류동', '가산동', '독산동', '시흥동', '공릉동', '상계.동', '상계동', '월계동', '중계.동',
       '중계동', '중계본동', '하계동', '도봉동', '방학동', '쌍문동', '창동', '답십리동', '용신동',
       '이문동', '장안동', '전농동', '제기동', '청량리동', '회기동', '휘경동', '노량진동', '대방동',
       '사당동', '상도동', '신대방동', '흑석동', '공덕동', '대흥동', '도화동', '망원동', '상암동',
       '서강동', '서교동', '성산동', '신수동', '아현동', '연남동', '염리동', '용강동', '합정동',
       '남가좌동', '북가좌동', '북아현동', '신촌동', '연희동', '천연동', '충현동', '홍은동', '홍제동',
       '내곡동', '반포동', '반포본동', '방배동', '방배본동', '서초동', '양재동', '잠원동', '금호.가동',
       '금호가동', '마장동', '사근동', '성수가동', '송정동', '옥수동', '왕십리도선동', '왕십리동',
       '용답동', '응봉동', '행당동', '길음동', '돈암동', '동선동', '보문동', '삼선동', '석관동',
       '성북동', '안암동', '월곡동', '장위동', '정릉동', '종암동', '가락동', '가락본동', '거여동',
       '마천동', '문정동', '방이동', '삼전동', '석촌동', '송파동', '오금동', '오륜동', '위례동',
       '잠실동', '잠실본동', '장지동', '풍납동', '목동', '신월동', '신정동', '당산동', '대림동',
       '도림동', '문래동', '신길동', '양평동', '여의동', '영등포동', '영등포본동', '남영동', '보광동',
       '서빙고동', '용문동', '용산가동', '원효로동', '이촌동', '이태원동', '청파동', '한강로동', '한남동',
       '효창동', '후암동', '갈현동', '구산동', '녹번동', '대조동', '불광동', '수색동', '역촌동',
       '응암동', '증산동', '진관동', '가회동', '교남동', '무악동', '부암동', '사직동', '삼청동',
       '숭인동', '이화동', '종로...가동', '종로·가동', '창신동', '청운효자동', '평창동', '혜화동',
       '광희동', '다산동', '동화동', '명동', '소공동', '신당동', '약수동', '을지로동', '장충동',
       '중림동', '청구동', '필동', '황학동', '회현동', '망우동', '망우본동', '면목.동', '면목동',
       '면목본동', '묵동', '상봉동', '신내동', '중화동'], dtype=object)

In [36]:
#csv 파일로 저장
dfsg.to_csv("dongdf_merged.csv",mode='w')

In [37]:
dfsg

,기간,자치구,동,내국인 인구,외국인 인구,세대당인구,65세이상 내국인 인구,65세이상 외국인 인구,총 수급자,면적,인구밀도,독거노인 합계,출생,사망
0,2019,강남구,개포동,15710.666667,80.666667,254.666667,2188.666667,3.666667,194.666667,1.756667,8861.666667,374.333333,70.333333,44.333333
1,2019,강남구,논현동,22373.000000,475.000000,90.500000,2920.500000,6.500000,321.500000,1.360000,16967.500000,520.500000,106.500000,85.000000
2,2019,강남구,대치동,28092.000000,165.000000,280.333333,2830.000000,5.000000,129.000000,1.173333,26625.000000,330.333333,70.000000,64.000000
3,2019,강남구,도곡동,28395.500000,136.000000,277.000000,3598.500000,9.500000,65.000000,1.020000,27972.000000,474.500000,151.000000,81.000000
4,2019,강남구,삼성동,22549.500000,247.500000,236.000000,2679.500000,7.000000,177.000000,1.590000,16214.000000,400.000000,138.000000,61.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
244,2019,중랑구,면목본동,35341.000000,854.000000,2.000000,5729.000000,5.000000,1332.000000,1.010000,35837.000000,1245.000000,201.000000,191.000000
245,2019,중랑구,묵동,27750.000000,208.500000,230.000000,4329.500000,8.000000,567.500000,0.950000,29221.500000,765.000000,172.000000,126.500000
246,2019,중랑구,상봉동,22422.500000,249.000000,211.500000,3125.000000,6.000000,754.500000,0.765000,29590.500000,1274.000000,147.500000,100.000000
247,2019,중랑구,신내동,31266.500000,113.000000,257.500000,4959.000000,3.000000,860.000000,1.760000,19137.000000,1310.000000,173.500000,176.500000
248,2019,중랑구,중화동,23723.000000,372.000000,21.000000,4023.500000,11.000000,988.000000,0.830000,29295.000000,938.500000,139.500000,126.500000